pipeline{
    agent{
        dockerfile{
            dir '.'
            filename 'gradle.Dockerfile'
        }
    }
    stages{
        stage('Compile'){
            steps{
                dir("$WORKSPACE/calculator")
                sh '''
                    gradlew compileJava
                '''
            }
        }
        stage('Unit Tests'){
            steps{
                dir("$WORKSPACE/calculator")
                sh '''
                    gradlew test
                '''
            }
        }
    }
}