work_dir='Bootcamp Devops/EjerciciosEntrega/Modulo4/ejercicio1'
pipeline{
    agent{
        dockerfile{
            dir "$work_dir"
            filename 'gradle.Dockerfile'
        }
    }
    stages{
        stage('Compile'){
            steps{
                dir("$WORKSPACE/$work_dir/calculator"){
                    sh './gradlew compileJava'

                }
                
            }
        }
        stage('Unit Tests'){
            steps{
                dir("$WORKSPACE/$work_dir/calculator"){
                    sh './gradlew test'    
                }
                
            }
        }
    }
}